config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Ruta estática
  root to: 'pages#home'


  resources :products, only: [:index, :show, :new, :create]

  resources :orders, except: :index do
    member do
      get :check
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  monetize :unit_price_cents
  monetize :total_price_cents

  after_create_commit :update_total_price

  private

  def update_total_price
    q = self.cantidad
    unit_price = self.unit_price_cents
    total_price = unit_price * q

    update(total_price_cents: total_price)
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :line_items, dependent: :destroy
  belongs_to :user

  monetize :total_price_cents

  after_create_commit :update_total_price
  after_update_commit :update_total_price
  accepts_nested_attributes_for :line_items

  private

  def update_total_price
    line_items = self.line_items

    amount = 0
    line_items.sum(:total_price_cents) if line_items.size > 0

    update(total_price_cents: amount)
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :line_items

  monetize :price_cents

  has_one_attached :photo
  validates :category, inclusion: { in: ["Ramos de flores", "Arreglos florales", "Canastos, centros y cubreurnas", "Coronas", "Dias especiales"] }
end

app/models/semilla.rb
class Semilla < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user! 

    include Pundit

    # Pundit: white-list approach.
    after_action :verify_authorized, except: :index, unless: :skip_pundit?
    after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?
  
    # Uncomment when you *really understand* Pundit!
    # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
    # def user_not_authorized
    #   flash[:alert] = "You are not authorized to perform this action."
    #   redirect_to(root_path)
    # end
  
    private
  
    def skip_pundit?
      devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  def new
    @product = Product.find(params[:product_id])
    @cantidad = params[:cantidad]
    @order = current_user.orders.new
    @order.line_items.build
    @subtotal = @cantidad.to_i * @product.price_cents
    authorize @order
  end

  def create
    @order = current_user.orders.new(order_params)
    @order.status = "En Proceso"
    authorize @order
    if @order.save
      redirect_to order_path(@order)
    else
      render :new
    end
  end

  def show
    authorize @order
  end

  def edit
    authorize @order
  end

  def update
    authorize @order
  end

  def check
    @order = Order.find(params[:id])
    authorize @order
  end


  private

  def order_params
    params.require(:order).permit(:status, :user_id, :user, :total_price_cents, :destinatario, :telefono, :email_d, :direccion_de_envio, :comuna, :ciudad, :codigo_postal, line_items_attributes: [:order_id, :product_id,:total_price_cents,:cantidad, :unit_price_cents])
  end

  def set_order
    @order = Order.find(params[:id])
    authorize @order
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :product]

  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    @products= policy_scope(Product).order(created_at: :desc)
  end

  def show
    @product = Product.find(params[:id])
    authorize @product
  end

  def new
    @product = Product.new
    authorize @product
  end

  def create
    @product = Product.new(product_params)
    authorize @product

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Producto creado." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to product_url, notice: "Producto eliminado." }
      format.json { head :no_content }
    end
  end

  private
  def set_user
    @product = Product.find(params[:id])
    authorize @restaurant
  end

  def product_params
    params.require(:product).permit(:name, :content, :address, :country, :price_cents, :photo, :category)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "Usuario creado." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "Cambios en el usuario realizados." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "Usuario eliminado." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:id, :first_name, :last_name, :email, :password, :address, :username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categorias/index.html.erb
<h1>Categorias</h1>
<div class="container">
  <div class="d-flex justify-content-center aling-item-center">
    <% @products.each do |item| %>
      <div class="card-product ml-3">
           <%= cl_image_tag item.photo.key, crop: :fill %>
            <div class="card-product-infos">
              <h2><%=item.name%></h2>
              <p><%=item.content%></p>
              <h1>Categorias: <%= @item.category %></h1>
              <%= link_to 'Ver mas', product_path(item.id)%>
            </div>
          </div>
      <%end%>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Petalos Chile</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
 
    <!-- BOOSTRAP-->
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
    
  <!-- bootstrap css -->
      <link rel="stylesheet" href="../assets/stylesheets/css/bootstrap.min.css">
      <!-- style css -->
      <link rel="stylesheet" href="css/style.css">
      <!-- Responsive-->
      <link rel="stylesheet" href="css/responsive.css">
      <!-- fevicon -->
      <link rel="icon" href="images/fevicon.png" type="image/gif" />
      <!-- Scrollbar Custom CSS -->
      <link rel="stylesheet" href="css/jquery.mCustomScrollbar.min.css">
      <!-- Tweaks for older IEs-->




    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/alerts' %>

    <%# <p class="notice"><%= notice %>
    <%# <p class="alert"><%= alert %> 

    <%= yield %>
  </body>

  <!-- Javascript files-->

      <script src="../../javascript/packs/jquery.min.js"></script>
      <script src="../../javascript/packs/popper.min.js"></script>
      <script src="../../javascript/packs/bootstrap.bundle.min.js"></script>
      <script src="../../javascript/packs/jquery-3.0.0.min.js"></script>
      <script src="../..//javascript/packs/plugin.js"></script>
      <!-- sidebar -->
      <script src="../../javascript/packs/jquery.mCustomScrollbar.concat.min.js"></script>
      <script src="../../javascript/packs/custom.js"></script>
      <!-- javascript --> 
      <script src="../../javascrpts/packs/owl.carousel.js"></script>

      <script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
      <script>
         $(document).ready(function(){
         $(".fancybox").fancybox({
         openEffect: "none",
         closeEffect: "none"
         });
         
         $(".zoom").hover(function(){
         
         $(this).addClass('transition');
         }, function(){
         
         $(this).removeClass('transition');
         });
         });
         
      </script> 

</html>

app/views/orders/check.html.erb
<div class="container mt-5">
 <div class="d-flex justify-content-center mt-5">
    <h1>Resumen de Compra</h1>
 </div>
 <div class="d-flex justify-content-between aling-item-center border-bottom">
    <div class="text-center" >
      <i class="fas fa-3x fa-cart-plus"></i>
      <p>1. Añadir al Carro</p>
    </div>
    
    <div class="text-center" >
      <i class="far fa-3x fa-money-bill-alt"></i>
      <p>2. Pago</p>
    </div>

    <div class="text-center" id="active">
      <i class="fas fa-3x fa-clipboard-check"></i>
      <p>3. Confirmacion</p>
    </div>
  </div>
    <div class="row aling-items-center ">
        
        <div class="col-sm-12 text-center">
          <div class="card">
            <div class="card-body">
            <%= image_tag("confirmada.png", width: 300, crop: :fill) %>
            <h3>Orden confirmada</h3>
              <p class="card-text">Por favor espere un Email con el detalle de su orden</p>
    
            </div>
          </div>
        </div>
    </div>
</div>

app/views/orders/edit.html.erb
<h1>Orders#edit</h1>
<p>Find me in app/views/orders/edit.html.erb</p>

app/views/orders/new.html.erb
<div class="container mt-5">

  <div class="d-flex justify-content-between aling-item-center border-bottom mt-5">
    <div class="text-center" id="active">
      <i class="fas fa-3x fa-cart-plus"></i>
      <p>1. Añadir al Carro</p>
    </div>
    
    <div class="text-center">
      <i class="far fa-3x fa-money-bill-alt"></i>
      <p>2. Pago</p>
    </div>

    <div class="text-center">
      <i class="fas fa-3x fa-clipboard-check"></i>
      <p>3. Confirmacion</p>
    </div>
  </div>

  <div class="container">
    <div class="row mt-5">
    
    
    
      <div class="direccion_envio col-6">
        <h1>Direccion de Envio</h1>
          <%= simple_form_for(@order) do |f| %>
          <%= f.input :destinatario, label: "Destinatario" %>
        <%= f.input :telefono, label: "Telefono" %>
        <%= f.input :email_d, label: "Email Destinatario" %>
        <%= f.input :direccion_de_envio, label: "Direccion de envio" %>
        <%= f.input :comuna, label: "Comuna" %>
        <%= f.input :ciudad, label: "Ciudad" %>
        <%= f.input :codigo_postal, label: "Codigo Postal" %>
        <%= f.input :total_price_cents, as: :hidden, input_html: { value: @subtotal }  %>
        <%= f.simple_fields_for :line_items do |item| %>
          <%= item.input :product_id, as: :hidden, input_html: { value: @product.id} %>
          <%= item.input :unit_price_cents, as: :hidden, input_html: { value: @product.price_cents.to_i } %>
          <%= item.input :cantidad, input_html: { value: @cantidad } %>
        <% end %>
        <%= f.submit "Guardar",  class:"btn btn-primary m-1"  %>
      <% end %>
      </div>


      <div class="detalle_orden col-6">
            <h1>Detalle de Orden</h1>
            
             <div class="row align-items-center">
                  <%= cl_image_tag @product.photo.key,  :size => "260px"%>
             </div>
           
           <div>
        
            <h4>Producto: <span style="color:gray">  <%=   @product.name  %><span></h4>
            <h4><%=  @product.content  %></h4>
            <h4>Subtotal <span style="color:gray"> <%= @subtotal %> CLP <span></h4>
            <h4>Total Compra  <span style="color:gray"><%= @subtotal %> CLP <span> </h4>
           
           </div>

           

      
      </div>


    </div>
  </div>
</div>

app/views/orders/show.html.erb
<div class="container mt-5">
 <div class="d-flex justify-content-center mt-5">
    <h1>Resumen de Compra</h1>
 </div>
 <div class="d-flex justify-content-between aling-item-center border-bottom">
    <div class="text-center" >
      <i class="fas fa-3x fa-cart-plus"></i>
      <p>1. Añadir al Carro</p>
    </div>
    
    <div class="text-center" id="active">
      <i class="far fa-3x fa-money-bill-alt"></i>
      <p>2. Pago</p>
    </div>

    <div class="text-center">
      <i class="fas fa-3x fa-clipboard-check"></i>
      <p>3. Confirmacion</p>
    </div>
  </div>
    <div class="row aling-items-center mt-5">
      <div class="col-sm-6">
        <div class="card">
          <div class="card-body">
            <h5  class="card-title">Destinatario : <span style="color:gray">Total: <%= @order.total_price_cents %> CLP </span></h5>
            <h5 class="card-title">Destinatario : <span style="color:gray"> <%= @order.destinatario %></span></h5>
            <h5 class="card-title">Telefono : <span style="color:gray"> <%= @order.telefono %></span></h5>
            <h5 class="card-title">Email : <span style="color:gray"> <%= @order.email_d %></span></h5>
            <h5 class="card-title">Direccion de Envio : <span style="color:gray"> <%= @order.direccion_de_envio %></span></h5>
            <h5 class="card-title">Comuna :  <span style="color:gray"> <%= @order.comuna %></span></h5>
            <h5 class="card-title">Ciudad : <span style="color:gray"> <%= @order.ciudad %></span></h5>
            <h5 class="card-title">Codigo Postal : <span style="color:gray"> <%= @order.codigo_postal %></span></h5>
          
          </div>
        </div>
      </div>
      <div class="col-sm-6 text-center">
        <div class="card">
          <div class="card-body">
          <%= image_tag("webpay-plus-integracion.png", width: 300, crop: :fill) %>
          <br>
          <%= link_to'Pagar', check_order_path(@order), class:"btn btn-primary m-1"%>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">

    <%= f.input :name %>
    <%= f.input :content %>
    <%= f.input :address %>
    <%= f.input :country, as: :text %>
    <%= f.input :price_cents %>
    <%= f.input :photo, as: :file %>
    <%= f.input :category, collection: ["Ramos de flores", "Arreglos florales", "Canastos, centros y cubreurnas", "Coronas", "Dias especiales"] %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/products/index.html.erb
<h1>¡Todo tipo de arreglos florales para cualquier ocasión!</h1>
<div class="container">
  <div class="d-flex justify-content-center aling-item-center flex-wrap">
    <% @products.each do |item| %>
      <div class="card-product m-2">
           <%= cl_image_tag item.photo.key, crop: :fill %>
            <div class="card-product-infos">
              <h2><%=item.name%></h2>
              <p><%=item.content%></p>
              <h6>Precio: $ <%=item.price_cents%></h6>
              <%= link_to 'Ver mas', product_path(item.id)%>
            </div>
          </div>
      <%end%>
    </div>

<% if user_signed_in? && current_user.admin %>
  <%= link_to ' Crear Nuevo Producto', new_product_path  %>
<% end %>


</div>

app/views/products/new.html.erb
<h2>Nuevo Producto</h2>

<%= render 'form', user: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="container">
  <div class="card-product-detalle ml-3">
     <%= cl_image_tag @product.photo.key, crop: :fill %>
    <div class="card-product-detalle-infos">
      <div class="product-description">
      <%= form_with(url: new_order_path, method: :get) do |f| %>
        <div class="text-center mt-1 mb-1">
          <%= f.hidden_field :product_id, value: @product.id %>
          <h2><%=@product.name%></h2>
        </div>
        <div class="extra-margin">
          <p><%=@product.content%></p>
        </div>
        <div class="extra-margin">
          <h6>Precio $ <%=@product.price_cents%></h6>
        </div>
        <%= f.number_field :cantidad, value: "1", min: 1 %>
        <div class="d-flex justify-content-between mb-4">
          <%= link_to'Volver', products_path, class:"btn btn-primary m-1"%>
          <%= f.submit "Comprar", class:"btn btn-success  m-1" %>

        </div>
        <% end %>
     </div>
  </div>
</div>

app/views/shared/_alerts.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
  <!-- header -->
  <header>
      <!-- header inner -->
      <div class="header">
        <div class="container">
            <div class="row">
              <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col logo_section">
                  <div class="full">
                    <div class="center-desk">
                        <div class="logo"> <a href=""> <%= image_tag("logotipo.png", :alt => "rss feed") %></a> </div>
                    </div>
                  </div>
              </div>
              <div class="col-xl-9 col-lg-9 col-md-9 col-sm-9">
                  <div class="menu-area">
                    <div class="limit-box">
                        <nav class="main-menu">
                          <ul class="menu-area-main">
                              <% if user_signed_in? %>
                                <li class="active">  <%= link_to "Home", root_path(), class: "nav-link" %> </li>
                                <li> <%= link_to "Productos", products_path(), class: "nav-link" %> </li>
              
                                <li><a href="#gallery">Galeria</a></li>
                                <li><a href="#contact">Contactanos</a></li>
                                <li class="nav-item dropdown">
                                <%= image_tag "https://w7.pngwing.com/pngs/875/311/png-transparent-computer-icons-user-login-chang-miscellaneous-grass-area.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <%if user_signed_in? %>
                                  <p class="dropdown-item" >  <%= current_user.email  %></p>
                                  <% end %>
                                  <%= link_to "Cerrar sesion", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                                </div>
                                </li>
                       
                                
                                <% else %>
                                         <li class="active">  <%= link_to "Home", "#", class: "nav-link" %> </li>
                                          <li> <%= link_to "Productos", products_path(), class: "nav-link" %> </li>
                                          <li><a href="#gallery">Galeria</a></li>
                                          <li><a href="#contact">Contactanos</a></li>
                                            <li class="">
                                          <%= link_to "Tu cuenta", new_user_session_path, class: "" %>
                                        </li>
                                          <li class="last"><a href="#"> <%= image_tag("search_icon.png", :alt => "rss feed") %></a></li>
                                      
                                 <% end %>

                          </ul>
                        </nav>
                    </div>
                  </div>
              </div>
            </div>
        </div>
      </div>
      <!-- end header inner -->
  </header>
  <!-- end header -->

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :id %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :email %>
    <%= f.input :password %>
    <%= f.input :address %>
    <%= f.input :username %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editar</h1>

<%= render 'form', user: @user %>

<%= link_to 'Mostrar', @user %> |
<%= link_to 'Volver', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usuario</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Nombre</th>
      <th>Apellidos</th>
      <th>Email</th>
      <th>Usuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.username %></td>
        <td><%= link_to 'Mostrar', user %></td>
        <td><%= link_to 'Editar', edit_user_path(user) %></td>
        <td><%= link_to 'Eliminar', user, method: :delete, data: { confirm: '¿Estas seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Usuario', new_user_path %>

app/views/users/new.html.erb
<h1>Nuevo usuario</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @user.id %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>



<p>
  <strong>Direccion:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @user.username %>
</p>

<%= link_to 'Editar', edit_user_path(@user) %> |
<%= link_to 'Volver', users_path %>